language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: rZ6s77ubaocIdW7Fv0b9b/1MJP7mAJYfrN4/fB7rxtN3yrJlZt5H/pFgeaXmvepBVK14DfgkcPnZFR8pYJZ/ZjUV9be48u0ZHBM7Y6mAnY1nDUeyNk6utyzzT7Wqi1Anx2As2P/T4ckQ26S50JlBsDdP2b45UMmwzawoAk9XHiK1VvSa5yRzP1R6369xaLyCDwwyttBXkNC0WMeP2LDtc5iRR2CbqqWygGLItpgjDj+W/wvV+LLMXLkHTizDX43ukrqVTTO0q9j/6QMsCVGrIWypL7uLI6W0Ge0QjLmgthz2s/0bze7iDHFN221Uz5floLZYMFFcjDMpyyWUzUvRMzdH7Jw/5lUp+WJwrmcrZ90VIFmc2fNgSejb09t1yNUp7j2mQmbkFwxlnO4MW42NrFzmkx9VU0favvoF3j7Ov0iXVlFj4fHbwp5kE9M0SKuc+vvud2xrzMfKpxfuPKT5y4lfHb6mBmtUyokYEneIcSd03Ll4KOY8RdUE2bDHVacF+5Yyw3n42XylwBA9d20HjBlOncf4t5xW30J+LBZLnBqaaz9RYPK+xpvu5mWmv2Cxl3jfcZ7uCawle0lkdtDtzry7RmaFZDgqkT5zPfVDAf6DeaxjIDEAfzKX8mAPpXlmu8S5NardKr3Z/U5Q4hw0mPIcsyBOY/eU6hRET5mjxGo=
  app: linxify
  on:
    repo: jbvance/linxify
