language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: h2FeOtpiUbQWntW4GD1R1gpqA7+9QeYq4JfB9dz4Xt7EL81SpwxxCicBh7KLefX+nnkj0qBl+BwhGTMfO5ExtsrQunhEZqSJprUhfZY5ituThzrNhwmGGMLhv5XvgG9KwmhaEV9IJMP4mSPs4nD/KFyd+JckOd/IdmUV7Z7X5idTf+ylll0A2zXW9kgJIIG7RoCwa3GAQX+t3qyezkG7UcX9IFZUUNYJW3X0jehwlM+0SvnTABQmqLrzdU4w2psi4byKDvvisszZ/frdNj4byg8J8okc8nJjgG4noL7F3nYuDir8JzB+I10LS4zdkEpuAghvxBqYWEwZW8MvqRQ6k5oxpXfhO8aJZqUzl6QDDQDRe1GIQN/YLPRga0o5qITsBvwv2oyMmtos9LazV3FOWGZjn7Gx5X4FdqU5qDJlljM71pM3SD/X1gDdbiFfVdiGEG8GcXmRQk9IgHdF4i+W8A+AS5JklW3RqdCvV4Fcr3KifkY7BO5Ok25BLc1kec4jQ1DH5ft4WcG3Hy7Zf1thzo1zAm/u683fUrETDk+fmeJiVUtO6FDo5eOg/nskhbgrN7oli/8HAxJOKDvH1GvwrbtBAtM/ctYYDxbZh3/sdH9142EnyQodlVOwh1sApzwfMxX2LwbpFngq2KTLr7MK0pHkzPhMFBCep+F4Bz2+/sU=
  app: linxify-server
  on:
    repo: jbvance/linxify
